### ISSUE TITLE
Pretrained LNP models unclear naming

### ISSUE THREAD

**Issue by dvtailor** [YannDubs/Neural-Process-Family#7]
I could not find in your documentation what _"ELBOFalse_LatLBFalse_SigLBFalse"_ refers to. This is used to name the pretrained LNP models. Could you elaborate this

**Comment by YannDubs** [comment]
sorry, I somehow missed that. The notebook that generated those files is [this](https://github.com/YannDubs/Neural-Process-Family/blob/0b0f84a9c7bd218c8752e949bc61f8b2e7f822cd/jupyter/reproducibility/Losses.ipynb#L242)

LB is whether we set a lower bound for the predictive likelihood or the latent. ELBO is whether we are optimizing the ELBO instead of MLE. Details are in this [paper](https://arxiv.org/pdf/2007.01332.pdf)
